server:
  port: ${SPRING_DATASOURCE_PORT:8081}

spring:
  application:
    name: tictactoe

  datasource:
    driver-class-name: org.postgresql.Driver
#    password: postgres
#    url: jdbc:postgresql://localhost:5433/tictactoe?createDatabaseIfNotExist=true&useSSL=false
#    username: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tictactoe?createDatabaseIfNotExist=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#  security:
#    #nothing here in this project
